/*
Copyright 2025 pkhead

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation
files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy,
modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software
is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

#ifndef _beepbox_instrument_data_h_
#define _beepbox_instrument_data_h_

#define BPBX_INST_MAX_VOICES 16
#define BPBX_BASE_PARAM_COUNT 82

typedef enum {
    // basic params
    BPBX_PARAM_VOLUME,
    BPBX_PARAM_FADE_IN,
    BPBX_PARAM_FADE_OUT,

    // transition type params
    BPBX_PARAM_ENABLE_TRANSITION_TYPE,
    BPBX_PARAM_TRANSITION_TYPE,

    // chord type params
    BPBX_PARAM_ENABLE_CHORD_TYPE,
    BPBX_PARAM_CHORD_TYPE,

    // pitch shift params
    BPBX_PARAM_ENABLE_PITCH_SHIFT,
    BPBX_PARAM_PITCH_SHIFT,

    // detune params
    BPBX_PARAM_ENABLE_DETUNE,
    BPBX_PARAM_DETUNE,

    // vibrato params
    BPBX_PARAM_ENABLE_VIBRATO,
    BPBX_PARAM_VIBRATO_PRESET,
    BPBX_PARAM_VIBRATO_DEPTH,
    BPBX_PARAM_VIBRATO_SPEED,
    BPBX_PARAM_VIBRATO_DELAY,
    BPBX_PARAM_VIBRATO_TYPE,

    // note filter params
    BPBX_PARAM_ENABLE_NOTE_FILTER,
    BPBX_PARAM_NOTE_FILTER_ENABLED0,
    BPBX_PARAM_NOTE_FILTER_TYPE0,
    BPBX_PARAM_NOTE_FILTER_FREQ0,
    BPBX_PARAM_NOTE_FILTER_GAIN0,
    BPBX_PARAM_NOTE_FILTER_ENABLED1,
    BPBX_PARAM_NOTE_FILTER_TYPE1,
    BPBX_PARAM_NOTE_FILTER_FREQ1,
    BPBX_PARAM_NOTE_FILTER_GAIN1,
    BPBX_PARAM_NOTE_FILTER_ENABLED2,
    BPBX_PARAM_NOTE_FILTER_TYPE2,
    BPBX_PARAM_NOTE_FILTER_FREQ2,
    BPBX_PARAM_NOTE_FILTER_GAIN2,
    BPBX_PARAM_NOTE_FILTER_ENABLED3,
    BPBX_PARAM_NOTE_FILTER_TYPE3,
    BPBX_PARAM_NOTE_FILTER_FREQ3,
    BPBX_PARAM_NOTE_FILTER_GAIN3,
    BPBX_PARAM_NOTE_FILTER_ENABLED4,
    BPBX_PARAM_NOTE_FILTER_TYPE4,
    BPBX_PARAM_NOTE_FILTER_FREQ4,
    BPBX_PARAM_NOTE_FILTER_GAIN4,
    BPBX_PARAM_NOTE_FILTER_ENABLED5,
    BPBX_PARAM_NOTE_FILTER_TYPE5,
    BPBX_PARAM_NOTE_FILTER_FREQ5,
    BPBX_PARAM_NOTE_FILTER_GAIN5,
    BPBX_PARAM_NOTE_FILTER_ENABLED6,
    BPBX_PARAM_NOTE_FILTER_TYPE6,
    BPBX_PARAM_NOTE_FILTER_FREQ6,
    BPBX_PARAM_NOTE_FILTER_GAIN6,
    BPBX_PARAM_NOTE_FILTER_ENABLED7,
    BPBX_PARAM_NOTE_FILTER_TYPE7,
    BPBX_PARAM_NOTE_FILTER_FREQ7,
    BPBX_PARAM_NOTE_FILTER_GAIN7,

    // eq params (enabled, type, freq, gain)
    BPBX_PARAM_EQ_ENABLED0,
    BPBX_PARAM_EQ_TYPE0,
    BPBX_PARAM_EQ_FREQ0,
    BPBX_PARAM_EQ_GAIN0,
    BPBX_PARAM_EQ_ENABLED1,
    BPBX_PARAM_EQ_TYPE1,
    BPBX_PARAM_EQ_FREQ1,
    BPBX_PARAM_EQ_GAIN1,
    BPBX_PARAM_EQ_ENABLED2,
    BPBX_PARAM_EQ_TYPE2,
    BPBX_PARAM_EQ_FREQ2,
    BPBX_PARAM_EQ_GAIN2,
    BPBX_PARAM_EQ_ENABLED3,
    BPBX_PARAM_EQ_TYPE3,
    BPBX_PARAM_EQ_FREQ3,
    BPBX_PARAM_EQ_GAIN3,
    BPBX_PARAM_EQ_ENABLED4,
    BPBX_PARAM_EQ_TYPE4,
    BPBX_PARAM_EQ_FREQ4,
    BPBX_PARAM_EQ_GAIN4,
    BPBX_PARAM_EQ_ENABLED5,
    BPBX_PARAM_EQ_TYPE5,
    BPBX_PARAM_EQ_FREQ5,
    BPBX_PARAM_EQ_GAIN5,
    BPBX_PARAM_EQ_ENABLED6,
    BPBX_PARAM_EQ_TYPE6,
    BPBX_PARAM_EQ_FREQ6,
    BPBX_PARAM_EQ_GAIN6,
    BPBX_PARAM_EQ_ENABLED7,
    BPBX_PARAM_EQ_TYPE7,
    BPBX_PARAM_EQ_FREQ7,
    BPBX_PARAM_EQ_GAIN7,
} bpbx_inst_param_e;

#define BPBX_FM_PARAM_COUNT 11
#define BPBX_FM_FREQ_COUNT 35
#define BPBX_FM_ALGORITHM_COUNT 13
#define BPBX_FM_FEEDBACK_TYPE_COUNT 18

typedef enum {
    BPBX_FM_PARAM_ALGORITHM = BPBX_BASE_PARAM_COUNT,
    BPBX_FM_PARAM_FREQ1,
    BPBX_FM_PARAM_VOLUME1,
    BPBX_FM_PARAM_FREQ2,
    BPBX_FM_PARAM_VOLUME2,
    BPBX_FM_PARAM_FREQ3,
    BPBX_FM_PARAM_VOLUME3,
    BPBX_FM_PARAM_FREQ4,
    BPBX_FM_PARAM_VOLUME4,
    BPBX_FM_PARAM_FEEDBACK_TYPE,
    BPBX_FM_PARAM_FEEDBACK_VOLUME,
} bpbx_fm_param_e;

#endif